# Generated by Django 2.1.4 on 2019-05-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenttime', models.DateTimeField(null=True)),
                ('commenttext', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backtime', models.DateTimeField(null=True)),
                ('backtext', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordtime', models.DateTimeField(null=True)),
                ('comment', models.BooleanField()),
                ('feedback', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='userphone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='userphone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userphone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.users'),
        ),
    ]
